### ISSUE TITLE
Does not compile with openSCAD 2014.03

### ISSUE THREAD

**Issue by Lukelectro** [noisegate/box#1]
What version of openScad did you use?

It gives a syntax error on line 29: 

Parser error in line 29: syntax error
ERROR: Compilation failed!

Line 29 being function flatten(l) =  [for (a = l) for (b = a) b]  ;

Commenting that out and changing the lines where it is used gives a syntax error on the line(s) where tempx1 etc. get define, in their for loops.

Could it be OpenSCAD syntax changed between the versions we are using?

**Comment by noisegate** [comment]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/List_Comprehensions
